package com.smartFitness.itpm.Nutrition;
// Generated by Selenium IDE
//import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@SpringBootTest
public class NutritionistTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void nutritionist() {
        driver.get("http://localhost:4200/");
        driver.manage().window().setSize(new Dimension(826, 816));
        driver.findElement(By.cssSelector(".material-icons")).click();
        driver.findElement(By.cssSelector(".col-xl-6:nth-child(1) > .form-control")).click();
        driver.findElement(By.cssSelector(".ng-dirty:nth-child(2)")).sendKeys("2year");
        driver.findElement(By.cssSelector(".col-xl-6 > .ng-untouched")).click();
        driver.findElement(By.cssSelector(".col-xl-6 > .ng-untouched")).sendKeys("1 beans");
        driver.findElement(By.cssSelector(".form-select")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector(".form-select"));
            dropdown.findElement(By.xpath("//option[. = 'Weight Lost Diet Plans']")).click();
        }
        driver.findElement(By.cssSelector(".modal-footer > .btn-primary")).click();
        driver.findElement(By.cssSelector(".col-12:nth-child(2) .btn:nth-child(1) > .far")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".col-12:nth-child(2) .btn:nth-child(1) > .far"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".form-select")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector(".form-select"));
            dropdown.findElement(By.xpath("//option[. = 'Maintainance Diet Plans']")).click();
        }
        driver.findElement(By.cssSelector(".col-xl-6:nth-child(2) > .form-control")).click();
        driver.findElement(By.cssSelector(".col-xl-6:nth-child(2) > .form-control")).click();
        driver.findElement(By.cssSelector(".col-xl-6 > .ng-dirty")).sendKeys("100 beans");
        driver.findElement(By.cssSelector(".ng-untouched:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".ng-untouched:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".ng-untouched:nth-child(2)")).sendKeys("3 month");
        driver.findElement(By.cssSelector(".modal-footer > .btn-primary")).click();
        driver.findElement(By.cssSelector(".col-12:nth-child(2) .btn:nth-child(2) > .far")).click();
        driver.findElement(By.cssSelector(".swal2-confirm")).click();
    }
}
